### PR TITLE
Improved trainer checklist

### PR DESCRIPTION
**Pull request by mokaddem**

### CODE REVIEW

**Comment by iglocska** [comment]
Thanks a lot!

**Comment by adulau** [comment]
@iglocska The level of appreciation was already notified during the airport hackathon session with @mokaddem to improve the document and especially to enhance a training in an European member state.

**Comment by iglocska** [comment]
It's for transparency! We wouldn't want to look like jerks ;)

**Comment by adulau** [comment]
This transparency is key for our societies, especially in Europe where election will take place very soon. We hope to bring peace and good practices to the world at large.

**Pull request merged**
